server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: opslog-example-springboot-mvc
  datasource:
    url: jdbc:h2:mem:h2db
  h2:
    console:
      enabled: true
  flyway:
    locations: "classpath:db/migration/{vendor}"
